// =============================================================================
// 后台管理接口 - 通用消息定义
// =============================================================================
//
// 版本: v1.0
// 更新时间: 2026-02-05
// 用途: gRPC 后台管理接口的通用消息类型
//
// 本文件定义了所有 Admin 服务共用的基础消息类型：
// - ApiResponse: 通用 API 响应（用于无额外数据返回的操作）
// - Pagination: 分页请求参数
// - PageInfo: 分页响应信息
// - TimeRange: 时间范围筛选
// - Empty: 空消息
//
// =============================================================================

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: admin/admin_common.proto

package admin

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ApiResponse - 通用 API 响应
//
// 用于不需要返回额外业务数据的操作（如：激活用户、封禁用户等）
// 调用方应首先检查 code 字段判断操作是否成功
//
// 示例响应：
// - 成功: { code: 0, message: "激活成功" }
// - 失败: { code: 404, message: "用户不存在" }
// - 参数错误: { code: 400, message: "reason 参数必填" }
// - 认证失败: { code: 401, message: "缺少管理员身份信息 (x-admin-id)" }
// - 服务器错误: { code: 500, message: "内部错误: ..." }
type ApiResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 业务状态码
	// - 0: 成功
	// - 400: 参数错误（如缺少必填字段、参数值无效）
	// - 401: 认证失败（如缺少 x-admin-id）
	// - 404: 资源不存在（如用户不存在、邀请码不存在）
	// - 500: 服务器内部错误
	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	// 响应消息（中文）
	// 成功时返回操作结果描述，失败时返回错误原因
	Message       string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponse) Reset() {
	*x = ApiResponse{}
	mi := &file_admin_admin_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponse) ProtoMessage() {}

func (x *ApiResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_admin_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponse.ProtoReflect.Descriptor instead.
func (*ApiResponse) Descriptor() ([]byte, []int) {
	return file_admin_admin_common_proto_rawDescGZIP(), []int{0}
}

func (x *ApiResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ApiResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Pagination - 分页请求参数
//
// 用于列表查询请求中指定分页参数
// 如不传递，默认 page=1, page_size=20
type Pagination struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 页码，从 1 开始
	// 默认值: 1
	// 最小值: 1
	Page int32 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	// 每页数量
	// 默认值: 20
	// 最小值: 1
	// 最大值: 100
	PageSize      int32 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pagination) Reset() {
	*x = Pagination{}
	mi := &file_admin_admin_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pagination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pagination) ProtoMessage() {}

func (x *Pagination) ProtoReflect() protoreflect.Message {
	mi := &file_admin_admin_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pagination.ProtoReflect.Descriptor instead.
func (*Pagination) Descriptor() ([]byte, []int) {
	return file_admin_admin_common_proto_rawDescGZIP(), []int{1}
}

func (x *Pagination) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *Pagination) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// PageInfo - 分页响应信息
//
// 用于列表查询响应中返回分页状态
// 调用方可据此计算总页数: total_pages = ceil(total / page_size)
type PageInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 符合查询条件的总记录数
	Total int32 `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	// 当前页码（与请求参数一致）
	Page int32 `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	// 每页数量（与请求参数一致）
	PageSize      int32 `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageInfo) Reset() {
	*x = PageInfo{}
	mi := &file_admin_admin_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageInfo) ProtoMessage() {}

func (x *PageInfo) ProtoReflect() protoreflect.Message {
	mi := &file_admin_admin_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageInfo.ProtoReflect.Descriptor instead.
func (*PageInfo) Descriptor() ([]byte, []int) {
	return file_admin_admin_common_proto_rawDescGZIP(), []int{2}
}

func (x *PageInfo) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *PageInfo) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *PageInfo) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// TimeRange - 时间范围筛选
//
// 用于按时间范围筛选数据（如注册时间、激活时间）
// 时间戳为 Unix 时间戳（秒），UTC 时区
//
// 注意：
// - start 和 end 均为可选，可只传其一实现"之后"或"之前"筛选
// - 边界包含：start <= time <= end
// - 如 start > end，将返回空结果
//
// 示例：
//   - 查询 2026-01-01 至 2026-01-31 的数据:
//     { start: 1735689600, end: 1738367999 }
//   - 查询 2026-01-01 之后的数据:
//     { start: 1735689600 }
type TimeRange struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 开始时间戳（秒，UTC）
	// 包含边界：time >= start
	Start int64 `protobuf:"varint,1,opt,name=start,proto3" json:"start,omitempty"`
	// 结束时间戳（秒，UTC）
	// 包含边界：time <= end
	End           int64 `protobuf:"varint,2,opt,name=end,proto3" json:"end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeRange) Reset() {
	*x = TimeRange{}
	mi := &file_admin_admin_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeRange) ProtoMessage() {}

func (x *TimeRange) ProtoReflect() protoreflect.Message {
	mi := &file_admin_admin_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeRange.ProtoReflect.Descriptor instead.
func (*TimeRange) Descriptor() ([]byte, []int) {
	return file_admin_admin_common_proto_rawDescGZIP(), []int{3}
}

func (x *TimeRange) GetStart() int64 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *TimeRange) GetEnd() int64 {
	if x != nil {
		return x.End
	}
	return 0
}

// Empty - 空消息
//
// 用于无参数或无返回值的 RPC 方法（如：健康检查）
type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_admin_admin_common_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_admin_admin_common_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_admin_admin_common_proto_rawDescGZIP(), []int{4}
}

var File_admin_admin_common_proto protoreflect.FileDescriptor

const file_admin_admin_common_proto_rawDesc = "" +
	"\n" +
	"\x18admin/admin_common.proto\x12\x05admin\";\n" +
	"\vApiResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"=\n" +
	"\n" +
	"Pagination\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\"Q\n" +
	"\bPageInfo\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"3\n" +
	"\tTimeRange\x12\x14\n" +
	"\x05start\x18\x01 \x01(\x03R\x05start\x12\x10\n" +
	"\x03end\x18\x02 \x01(\x03R\x03end\"\a\n" +
	"\x05EmptyBDZBgithub.com/agent-sapient/immigration-chat-admin-idl-go/proto/adminb\x06proto3"

var (
	file_admin_admin_common_proto_rawDescOnce sync.Once
	file_admin_admin_common_proto_rawDescData []byte
)

func file_admin_admin_common_proto_rawDescGZIP() []byte {
	file_admin_admin_common_proto_rawDescOnce.Do(func() {
		file_admin_admin_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_admin_admin_common_proto_rawDesc), len(file_admin_admin_common_proto_rawDesc)))
	})
	return file_admin_admin_common_proto_rawDescData
}

var file_admin_admin_common_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_admin_admin_common_proto_goTypes = []any{
	(*ApiResponse)(nil), // 0: admin.ApiResponse
	(*Pagination)(nil),  // 1: admin.Pagination
	(*PageInfo)(nil),    // 2: admin.PageInfo
	(*TimeRange)(nil),   // 3: admin.TimeRange
	(*Empty)(nil),       // 4: admin.Empty
}
var file_admin_admin_common_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_admin_admin_common_proto_init() }
func file_admin_admin_common_proto_init() {
	if File_admin_admin_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_admin_admin_common_proto_rawDesc), len(file_admin_admin_common_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_admin_admin_common_proto_goTypes,
		DependencyIndexes: file_admin_admin_common_proto_depIdxs,
		MessageInfos:      file_admin_admin_common_proto_msgTypes,
	}.Build()
	File_admin_admin_common_proto = out.File
	file_admin_admin_common_proto_goTypes = nil
	file_admin_admin_common_proto_depIdxs = nil
}
